### Register a new user
POST http://localhost:5432/auth/register
Content-Type: application/json

{
  "email" : "testmail@example.com",
  "password": "SecurePassword123;)",
  "full name": "Jhon Smith"
}

###